name: chumian_music
description: 初眠音乐 - Neumorphism design music player
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  just_audio: ^0.9.40
  dio: ^5.7.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  path_provider: ^2.1.4
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
